#!/usr/bin/env sh

# aquest script utiliza "mpc"

# ses dades són a partir de sa 2na columna
text=$(mpc current)
icon=$(mpc | grep "\[playing\]" > /dev/null && echo "" || echo "ﭦ")

if [ -n "$text" ]; then
    echo "$COL_VERD$icon $text"
else
    echo "$COL_BG_0-"
fi
