static const char black[]       = "#282828";
static const char white[]       = "#ebdbb2";
static const char gray2[]       = "#a89984"; // unfocused window border
static const char gray3[]       = "#928374";
static const char gray4[]       = "#1d2021";
static const char blue[]        = "#458588";  // focused window border
static const char green[]       = "#98971a";
static const char red[]         = "#cc241d";
static const char orange[]      = "#d65d0e";
static const char yellow[]      = "#d1b171";
static const char greenish_blue[]= "#8ec07c";
static const char gold[]       = "#DAA520";
static const char pink[]        = "#b16286";
static const char col_borderbar[]  = "#1e2122"; // inner border
