static const char black[]       = "#1d2021";
static const char white[]       = "#d4be98";
static const char gray2[]       = "#A9A9A9"; // unfocused window border
static const char gray3[]       = "#928374";
static const char gray4[]       = "#17191a";
static const char blue[]        = "#7daea3";  // focused window border
static const char green[]       = "#a9b665";
static const char red[]         = "#ea6962";
static const char orange[]      = "#FCAB6A";
static const char yellow[]      = "#d8a657";
static const char cyan[]        = "#89b482";
static const char gold[]        = "#DAA520";
static const char pink[]        = "#d3869b";
static const char col_borderbar[]  = "#1e2122"; // inner border
