#!/bin/sh

# Syncs repositories and downloads updates, meant to be run as a cronjob.

notify-send "📦 Repository Sync" "Checking for package updates..."

doas pacman -Syy --noconfirm || notify-send "Error downloading updates.

Check your internet connection, if pacman is already running, or run update manually to see errors."
pkill -RTMIN+8 "${STATUSBAR:-dwmblocks}"
