#font=JetBrainsMono:size=12
font=iosevka:size=14

[colors]
alpha=0.97
foreground=cdd6f4
background=1e1e2e

regular0=45475a
regular1=f38ba8
regular2=a6e3a1
regular3=f9e2af
regular4=89b4fa
regular5=f5c2e7
regular6=94e2d5
regular7=bac2de

bright0=585b70
bright1=f38ba8
bright2=a6e3a1
bright3=f9e2af
bright4=89b4fa
bright5=f5c2e7
bright6=94e2d5
bright7=a6adc8

selection-foreground=cdd6f4
selection-background=414356

search-box-no-match=11111b f38ba8
search-box-match=cdd6f4 313244

jump-labels=11111b fab387
urls=89b4fa

[scrollback]
lines=1000
multiplier=3.0
indicator-position=relative

[url]
launch=xdg-open ${url}
label-letters=sadfjklewcmpgh
osc8-underline=url-mode
protocols=http, https, ftp, ftps, file
[cursor]
style=underline
#color=#f5e0dc
blink=no
beam-thickness=1

[mouse]
hide-when-typing=yes



[key-bindings]
scrollback-up-page=Shift+Page_Up
scrollback-down-page=Shift+Page_Down
clipboard-copy=Control+Shift+c
clipboard-paste=Control+Shift+v
show-urls-launch=Control+Shift+y
show-urls-copy=Control+Shift+u
unicode-input=none
search-start=Control+Shift+r

[search-bindings]
cancel=Control+g Control+c Escape
commit=Return
find-prev=Control+r
find-next=Control+s
cursor-left=Left Control+b
cursor-left-word=Control+Left Mod1+b
cursor-right=Right Control+f
cursor-right-word=Control+Right Mod1+f
cursor-home=Home Control+a
cursor-end=End Control+e
delete-prev=BackSpace
delete-prev-word=Mod1+BackSpace Control+BackSpace
delete-next=Delete
delete-next-word=Mod1+d Control+Delete
extend-to-word-boundary=Control+w
extend-to-next-whitespace=Control+Shift+w
clipboard-paste=Control+v Control+y
primary-paste=Control+V
